# Generated by Django 3.1.2 on 2022-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion')),
                ('fecha_publicacion', models.DateField(verbose_name='fecha_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_i', models.DateField(verbose_name='fecha_inicio')),
                ('fecha_f', models.DateField(verbose_name='fecha_fin')),
                ('duracion', models.PositiveIntegerField(verbose_name='duracion')),
                ('titulo', models.CharField(max_length=60, verbose_name='titulo')),
            ],
        ),
    ]
