# Generated by Django 3.1.2 on 2022-02-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='fecha_f',
            field=models.DateTimeField(verbose_name='fecha_fin'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='fecha_i',
            field=models.DateTimeField(verbose_name='fecha_inicio'),
        ),
    ]
