# Generated by Django 3.0.3 on 2022-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0002_auto_20220212_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='fecha_f',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(upload_to='Anuncios'),
        ),
    ]
